### PR TITLE
Space travelers WebSite

### PR DESCRIPTION
**Pull request by Sirvelasque**
- Created the homepage leading to the "Rockets" section
  - It let you make a reservation and show changes on time
- Created a "Missions" sections
  - Shows a list of missions and allow to join them showing changes on time
- Created a "My Profile" section
  - Shows both reservated Rockets and Joined missions and it updates on time
- All the information is taked from the provided APIs

### CODE REVIEW

**Review by codepantha — CHANGES_REQUESTED** [review]
Hi team 👋,

## STATUS: REQUESTED CHANGES ♻️  

You have done a terrific job so far👏! However, there are some issues that you still need to work on to go to the next project but you are almost there 👍 



### Highlights ⭐ 🎯
✔️ Descriptive PR
✔️ Meaningful commit messages
✔️ Very good collaboration
✔️ Linter checks

## Required Changes ♻️
_Check the comments under the review._

- [ ] Testing is a project requirement. Please write unit tests with React Testing Library and Jest (for unit tests)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Moving your redux folder outside the components folder. I think it would be better and even more logical to have your redux folder directly in your `src/` folder. 😎 
- [ ] You can make your project better by rendering a placeholder message when there are no missions joined or no rockets reserved on your `MyProfile` component.
- [ ] If you like, I think it will improve the user experience of your app if users can `Cancel Reservation` or `Leave Mission` directly from the corresponding lists in your `MyProfile` component 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by codepantha** [comment]
@zkr024 I just realized that you pushed some changes after you had submitted your code for a review. I don't think that is a great idea 🚫 
Please endeavor not to modify your code once it has been submitted for review in order not to cause any sort of confusion.

Please go ahead and request for another review 🙏

**Comment by zkr024** [comment]
> @zkr024 I just realized that you pushed some changes after you had submitted your code for a review. I don't think that is a great idea 🚫 Please endeavor not to modify your code once it has been submitted for review in order not to cause any sort of confusion.
> 
> Please go ahead and request for another review 🙏

@codepantha sorry about that...I noticed about the Tests too late. Won't happen again

**Comment by codepantha** [comment]
It's alright @zkr024 👍 I'm glad you understand.
Happy coding 💻

**Review by andersonlebon — APPROVED** [review]
## Hi @team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

nodding-yes

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is  professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
